name: publish-empiarreader-to-pypi

on: push

jobs:
  build:
    name: build-dist
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.4"
    - name: install-pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: build-bin-whl
      run: python3 -m build
    - name: grab-build
      uses: actions/upload-artifact@v4
      with:
        name: pkg-dist
        path: dist/

  publish-to-pypi:
    name: >-
      publish-to-pypi
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/empiarreader
    permissions:
      id-token: write

    steps:
    - name: download-dists
      uses: actions/download-artifact@v4
      with:
        name: pkg-dist
        path: dist/
    - name: publish-dist-to-pypi
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-test-pypi:
    name: publish-to-test-pypi
    if: startsWith(github.ref, 'refs/heads/development')
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testing
      url: https://test.pypi.org/p/empiarreader

    permissions:
      id-token: write
    
    steps:
    - name: download-dists
      uses: actions/download-artifact@v4
      with:
        name: pkg-dist
        path: dist/
    - name: publish-dist-to-test-pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/